---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an S3 bucket with parameter section and output section

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to be created
    Default: my-s3-bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: S3BucketName
